### ISSUE TITLE
Möglichkeit schaffen um Bilder zu importieren. 

### ISSUE THREAD

**Issue by middle-way-approach** [middle-way-approach/Kassensystem#3]
Für die Produkte sollen Bilder hinterlegt werden können. Dazu müssen Bilder auf dem Device über die App aufrufbar sein.

**Comment by Conrad99** [comment]
- keine interne Kamera einbauen

- Bilder müssen importiert werden, Format, Größe etc. muss noch festgelegt werden

**Comment by middle-way-approach** [comment]
Man kann es einfach über einen Dialog lösen, in dem ich Bilder auf dem Handy auswählen kann (USB-Karte).
